### ISSUE TITLE
quants_mat.gz is not a directory

### ISSUE THREAD

**Issue by yueli8** [COMBINE-lab/minnow#7]
Hello, hiraksarkar,

Thank you for developing so great software.

I tried to import `quants_mat.gz` to Cell V Gene dataframe, followed:

https://combine-lab.github.io/alevin-tutorial/2018/output-format/

```
li@li-HP-Pavilion-Desktop-590-p0xxx:~$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vpolo.alevin import parser
>>> alevin_df = parser.read_quants_bin("</home/li/quants_mat.gz>")
</home/li/quants_mat.gz> is not a directory
```

I have something wrong in my python3 path?

```
li@li-HP-Pavilion-Desktop-590-p0xxx:~$ which python3
/usr/bin/python3
li@li-HP-Pavilion-Desktop-590-p0xxx:~$ whereis python3
python3: /usr/bin/python3.6m-config /usr/bin/python3.7 /usr/bin/python3.7m /usr/bin/python3.6 /usr/bin/python3.6-config /usr/bin/python3 /usr/bin/python3.6m /usr/lib/python3.7 /usr/lib/python3.6 /usr/lib/python3.8 /usr/lib/python3 /etc/python3.7 /etc/python3.6 /etc/python3 /usr/local/lib/python3.7 /usr/local/lib/python3.6 /usr/include/python3.6 /usr/include/python3.6m /usr/share/python3 /usr/share/man/man1/python3.1.gz
```

Thank you in advance for your great help!

Best,

yue

**Comment by k3yavi** [comment]
Hi @yueli711 ,

You have to provide the path to the output directory of alevin i.e. the path you gave with -o while running alevin.

**Comment by yueli8** [comment]
Hello, k3yavi,

Thank you so much for your quick response!

I followed: 

https://gist.github.com/k3yavi/c501705ed2d29b12b0d10cf78b3ed001

`-o alevin_output`

```
li@li-HP-Pavilion-Desktop-590-p0xxx:~$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vpolo.alevin import parser
>>> alevin_df = parser.read_quants_bin("</home/li/salmon-latest_linux_x86_64/bin/alevin_output>")
</home/li/salmon-latest_linux_x86_64/bin/alevin_output> is not a directory
```


Thank you for your great help!

Best,

Yue

**Comment by k3yavi** [comment]
Not sure what's going wrong.
Can you share the step by step command and logs you get ?

**Comment by yueli8** [comment]
Hello k3yavi,

Thank you for your message!

Alevin runs perfect!

Please see attached  alevin_output.zip file.


```
li@li-HP-Pavilion-Desktop-590-p0xxx:~/salmon-latest_linux_x86_64/bin$ ./salmon alevin -lISR -1 fastqs/pbmc_1k_v3_S1_L001_R1_001.fastq.gz -2 fastqs/pbmc_1k_v3_S1_L001_R2_001.fastq.gz --chromium -i index -p 8 -o alevin_output --tgMap txp2gene.tsv
Version Info: ### PLEASE UPGRADE SALMON ###
### A newer version of salmon with bug fixes is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and bug fixes; please upgrade at your
earliest convenience.
###
Sign up for the salmon mailing list to hear about new versions, features and updates at:
https://oceangenomics.com/subscribe
###
Logs will be written to alevin_output/logs
[2020-02-25 00:18:09.527] [alevinLog] [info] Loading Header
[2020-02-25 00:18:09.527] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2020-02-25 00:18:09.527] [jointLog] [info] Usage of --validateMappings implies use of minScoreFraction. Since not explicitly specified, it is being set to 0.65
[2020-02-25 00:18:09.527] [jointLog] [info] Usage of --validateMappings, without --hardFilter implies use of range factorization. rangeFactorizationBins is being set to 4
[2020-02-25 00:18:09.527] [jointLog] [info] Usage of --validateMappings implies a default consensus slack of 0.2. Setting consensusSlack to 0.2.
[2020-02-25 00:18:09.527] [jointLog] [info] Using default value of 0.87 for minScoreFraction in Alevin
Using default value of 0.6 for consensusSlack in Alevin
[2020-02-25 00:18:09.549] [alevinLog] [info] Loading Transcript Info 
### alevin (dscRNA-seq quantification) v0.14.1
### [ program ] => salmon 
### [ command ] => alevin 
### [ libType ] => { ISR }
### [ mates1 ] => { fastqs/pbmc_1k_v3_S1_L001_R1_001.fastq.gz }
### [ mates2 ] => { fastqs/pbmc_1k_v3_S1_L001_R2_001.fastq.gz }
### [ chromium ] => { }
### [ index ] => { index }
### [ threads ] => { 8 }
### [ output ] => { alevin_output }
### [ tgMap ] => { txp2gene.tsv }


[2020-02-25 00:18:09.671] [alevinLog] [info] Found all transcripts to gene mappings
[2020-02-25 00:18:09.681] [alevinLog] [info] Processing barcodes files (if Present) 

 
processed 33 Million barcodes

[2020-02-25 00:18:58.276] [alevinLog] [info] Done barcode density calculation.
[2020-02-25 00:18:58.276] [alevinLog] [info] # Barcodes Used: 33412667 / 33436697.
[2020-02-25 00:19:01.233] [alevinLog] [info] Knee found left boundary at  1442 
[2020-02-25 00:19:01.536] [alevinLog] [info] Gauss Corrected Boundary at  1179 
[2020-02-25 00:19:01.536] [alevinLog] [info] Learned InvCov: 122.212 normfactor: 398.84
[2020-02-25 00:19:01.536] [alevinLog] [info] Total 1768(has 588 low confidence) barcodes
[2020-02-25 00:19:01.566] [alevinLog] [info] Done True Barcode Sampling
[2020-02-25 00:19:01.646] [alevinLog] [info] Total 8.78893% reads will be thrown away because of noisy Cellular barcodes.
[2020-02-25 00:19:01.724] [alevinLog] [info] Done populating Z matrix
[2020-02-25 00:19:01.729] [alevinLog] [info] Total 24506 CB got sequence corrected
[2020-02-25 00:19:01.730] [alevinLog] [info] Done indexing Barcodes
[2020-02-25 00:19:01.730] [alevinLog] [info] Total Unique barcodes found: 655211
[2020-02-25 00:19:01.730] [alevinLog] [info] Used Barcodes except Whitelist: 23892
[2020-02-25 00:19:01.758] [alevinLog] [info] Done with Barcode Processing; Moving to Quantify

[2020-02-25 00:19:01.780] [alevinLog] [info] parsing read library format
[2020-02-25 00:19:01.861] [stderrLog] [info] Loading Suffix Array 
[2020-02-25 00:19:01.780] [jointLog] [info] There is 1 library.
[2020-02-25 00:19:01.860] [jointLog] [info] Loading Quasi index
[2020-02-25 00:19:01.861] [jointLog] [info] Loading 32-bit quasi index
[2020-02-25 00:19:10.476] [stderrLog] [info] Loading Transcript Info 
[2020-02-25 00:19:14.689] [stderrLog] [info] Loading Rank-Select Bit Array
[2020-02-25 00:19:15.519] [stderrLog] [info] There were 99,611 set bits in the bit array
[2020-02-25 00:19:15.566] [stderrLog] [info] Computing transcript lengths
[2020-02-25 00:19:15.566] [stderrLog] [info] Waiting to finish loading hash
[2020-02-25 00:19:23.242] [jointLog] [info] done
[2020-02-25 00:19:23.242] [jointLog] [info] Index contained 99,611 targets




processed 33 Million fragmentserrLog] [info] Done loading index
hits: 51209284, hits per frag:  1.55215



[2020-02-25 00:25:28.036] [jointLog] [info] Computed 83,984 rich equivalence classes for further processing
[2020-02-25 00:25:28.036] [jointLog] [info] Counted 15,204,698 total reads in the equivalence classes 
[2020-02-25 00:25:28.036] [jointLog] [info] Number of fragments discarded because they are best-mapped to decoys : 0
[2020-02-25 00:25:28.036] [jointLog] [warning] Found 1485 reads with `N` in the UMI sequence and ignored the reads.
Please report on github if this number is too large
[2020-02-25 00:25:28.036] [jointLog] [info] Mapping rate = 45.4731%

[2020-02-25 00:25:28.036] [jointLog] [info] finished quantifyLibrary()
[2020-02-25 00:25:28.248] [alevinLog] [info] Starting optimizer

Analyzed 1767 cells (100% of all).
[2020-02-25 00:25:44.647] [alevinLog] [info] Total 6812967.00 UMI after deduplicating.
[2020-02-25 00:25:44.647] [alevinLog] [info] Total 1462181 BiDirected Edges.
[2020-02-25 00:25:44.647] [alevinLog] [info] Total 102965 UniDirected Edges.
[2020-02-25 00:25:44.647] [alevinLog] [warning] Skipped 31 barcodes due to No mapped read
[2020-02-25 00:25:44.650] [alevinLog] [info] Clearing EqMap; Might take some time.
[2020-02-25 00:25:45.426] [alevinLog] [info] Starting white listing of 1736 cells
[2020-02-25 00:25:45.442] [alevinLog] [info] Starting to make feature Matrix
[2020-02-25 00:25:45.448] [alevinLog] [info] Done making feature Matrix
0.00270001	0.000198879	6.84675e-05	424401	13968.9	0.00436361	
0.0459976	0.0633981	0.0370491	4610.87	306.055	207.085	
[2020-02-25 00:25:45.590] [alevinLog] [info] Finished white listing
[2020-02-25 00:25:45.612] [alevinLog] [info] Finished optimizer

```
But it said:

```
li@li-HP-Pavilion-Desktop-590-p0xxx:~$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vpolo.alevin import parser
>>> alevin_df = parser.read_quants_bin("</home/li/salmon-latest_linux_x86_64/bin/alevin_output>")
</home/li/salmon-latest_linux_x86_64/bin/alevin_output> is not a directory
```

Thank you so much for your great  help!

Best,

Yue
[alevin_output.zip](https://github.com/COMBINE-lab/minnow/files/4248194/alevin_output.zip)

**Comment by k3yavi** [comment]
Oh can you remove `<` and '>' from the path you are providing to vpolo

**Comment by yueli8** [comment]
Hello, k3yavi,

Thank you so much for your suggestion!

It works perfect!

```
li@li-HP-Pavilion-Desktop-590-p0xxx:~$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vpolo.alevin import parser
>>> alevin_df = parser.read_quants_bin("/home/li/salmon-latest_linux_x86_64/bin/alevin_output")
/home/li/salmon-latest_linux_x86_64/bin/alevin_output/alevin
 Done reading 1700 cells
Read total 1736 cells
Found total 6812967.000422614 reads

```

In the manual:

https://combine-lab.github.io/alevin-tutorial/2018/output-format/

Alevin’s quants_mat.gz file can be easily imported to generate Cell v Gene dataframe using the following piece of python3 code:

Where is the Cell v Gene dataframe?

Thank you again!

Best,

Yue

**Comment by k3yavi** [comment]
alevin_df is the dataframe you just imported.

**Comment by k3yavi** [comment]
Closing the issue as it is getting imported now.

**Comment by yueli8** [comment]
Hello, k3yavi,

Thank you so much for your great help!

I just tried to change the `quants_mat.gz` file to human read.

I waited` ... `for so long time, then I typed `alevin_df = mmread("/home/li/salmon-latest_linux_x86_64/bin/alevin_output").toarray()` .

Is that possible I have to wait still `...`? I got confusing about the commands.

Thank you again!

Best,

Yue

```

li@li-HP-Pavilion-Desktop-590-p0xxx:~$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vpolo.alevin import parser
>>> alevin_df = parser.read_quants_bin("/home/li/salmon-latest_linux_x86_64/bin/alevin_output")
/home/li/salmon-latest_linux_x86_64/bin/alevin_output/alevin
 Done reading 1700 cells
Read total 1736 cells
Found total 6812967.000422614 reads
>>> from scipy.io import mmread
>>> import gzip
>>> with gzip.open(mat_file) as f:
... alevin_df = mmread("/home/li/salmon-latest_linux_x86_64/bin/alevin_output").toarray()
  File "<stdin>", line 2
    alevin_df = mmread("/home/li/salmon-latest_linux_x86_64/bin/alevin_output").toarray()
            ^
IndentationError: expected an indented block
```

**Comment by k3yavi** [comment]
Unfortunately, I do not understand what you are trying to do ?
If it's possible to share what's the motivation, what's the input and what's the output you are looking for, may be I can help better .
Basically the quants_mat.gz is a binary file, you can't gzip open it that's why we have the vpolo parser. If you are familiar with the pandas dataframe, the alevin_df you get is actually a pandas dataframe with cell v gene count matrix.

**Comment by yueli8** [comment]
Hello, k3yavi,

So sorry to bother you again and again.

The output files in alevin_output/alevin has: `quants_mat_cols.txt`, `quants_mat_cols.txt` and `quants_mat.gz.` 

I followed: 
https://combine-lab.github.io/alevin-tutorial/2018/output-format/.

Alevin’s quants_mat.gz file can be easily imported to generate Cell v Gene dataframe using the following piece of python3 code:

If alevin_df is cell v gene count matrix, how I can get alevin_df file and change to csv file?

```
>>> df.to_csv(alevin_df, sep='\t')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'df' is not defined
```


Thank you again and so sorry about that.

Best,

yue

**Comment by k3yavi** [comment]
Try alevin_df.to_csv("counts.txt", sep="\t")

**Comment by yueli8** [comment]
Hello, k3yavi,

That works!

Thank you for your: not only the wisdom to developing so great software, but also the patience to help the stranger like me!

Thank  you again!

Best,

Yue
